language: node_js
node_js:
  - node
deploy:
  provider: s3
  access_key_id: AKIA3XBPUQTKMIUEZFSZ
  secret_access_key:
    secure: Nno8QCh3cF2HBHSWEklcUUnAIIbWoVpYdyDAD2fykuHZ7cSLXckfySRADMSugkr7jDtrwTDqH/W3g6ov3jurHqcA+p7UAFHwXe+PvcLeXDH2RXFOrmVMJUWs4XDbycgt3RxisFTPKVvIS9g+OkkQg/r4sO/43XGJcGvixg+hwym5xT3kPPnMDhj8A27nDLylWELC4SJNgpF4AuAhsvuoDw9IscLFeUhxgqfGh+/pUqdEIs7T1DNt6gQbDlpHcpWXB3SCvjbQJ/qg8OvyHLplmxtKzT50ifDzZxefLUcO/yOfYLp/zzJga5DOTVnDm/kQzJyHlutJZ22CfFYP6qBPiQwHk6bA1KPNvzDDVQ9jFG7IlrgHHJycvaDRrruybS8t/V0tJH6l9hK+RJkqc63k6OQeXGnFtEj/kgAPoLBzbz3md8nMuc4mBhMIRcoJGatgnr3+bA3qPHl9NQhb556JZCRDf/+jRvnegnBDjU+INAgfkESR7wIccbnRJiqdOhUol2WOfIMpzcm8ULpnASMfe2KLo6wf26c//gFmuoBnGxLsQGjrh8B0H2TQ6PFKCyQ5mTZuHULFdc3KuQ3gFBF8Zc18JPlVRRiBkPHDOq12hUqGQ4yMURcV4mazayKbF4fgJ9syYSj6wZ/Gjwim2bvJ5ogtHNI/AXCJD9k4fpftC5Q=
  bucket: plusmin.us
  local-dir: plusmin.us
  acl: ''
  on:
    repo: chrisdeaner/plusminuswebsite
    branch: travis
