language: node_js
node_js:
- node
deploy:
  provider: s3
  edge: true
  bucket: plusmin.us
  skip_cleanup: true
  region: us-west-2
  local-dir: plusmin.us
  acl: public_read_write
  on:
    repo: chrisdeaner/plusminuswebsite
    branch: master
